### ISSUE TITLE
Test out the Salesforce Reporting Functionality

### ISSUE THREAD

**Issue by brettevans** [codefordenver/rmmfi#16]
Hayden and Amer

**Comment by haydenevans** [comment]
I went ahead and created a "Volunteer Rating" report that grabs leads that have been rated "Warm" or "Hot". The report sorts them ascending based on rating and also includes relevant information like position and industry. A similar report could be used in a scenario where Brendan needs to find good/highly rated replacement volunteers to fill a volunteer roster.

**Comment by haydenevans** [comment]
For further work on this, we will need leads or contacts with relevant custom fields pertaining to RMMFI's specific use cases

**Comment by wdoug** [comment]
Demoed 6/15/2015
