### ISSUE TITLE
Add fake contacts to sandbox

### ISSUE THREAD

**Issue by switzersc** [codefordenver/rmmfi#26]
Jen, Brian, Shelby, Vince, David, Matilda, Cameron -- all to fill our 5 contacts each.

**Comment by biodavis** [comment]
esp. the new fields that Michael Force filled out:
Donor Lifetime tracker total
Referral person
Class Rank (A, B, C, or X)
Skills-(business/entrepreneur, Coach ,and Finance)
There is a concept of "availability for class (dates, or yes and no for  certain period.  There is also a concept of "Class Roster" made of committed volunteers.  MF said this could possibly be done with the "session" construct they have now for Clients, but we can show this to Brendan next week to see if he likes it.
