### ISSUE TITLE
Ability to manually send survey

### ISSUE THREAD

**Issue by switzersc** [codefordenver/rmmfi#31]
As a member of RMMFI, I would like to be able to select a common email template to send to a community member so that I can easily target them with the right information.
- push of button to send contact the volunteer survey or a different survey
- have email tool that defaults to email template/survey they usually want, but has dropdown for user to select which email template/survey they want to send

**Comment by wdoug** [comment]
One request was for a dropdown to select the email template

**Comment by dkoloditch** [comment]
Here's the process using existing tools:
1. Navigate to Leads section
2. Click on the lead of interest
3. In the Email section near the bottom of the lead's page, click Send an Email
4. Below the Body field, click Select Template
5. Choose a template
6. Click Send

Custom buttons can be created and placed on Lead/Contact pages to quickly email. Requires a little JavaScript manipulation, but nothing complicated. See: https://success.salesforce.com/ideaView?id=087300000006tqzAAA

**Comment by wdoug** [comment]
##
