### ISSUE TITLE
Lead capture form

### ISSUE THREAD

**Issue by switzersc** [codefordenver/rmmfi#33]
As a member of RMMFI I would love to have a sign in form that feeds back to Salesforce for people that sign in at events so those contacts and data can be collected.

volunteer fills out new contact form themselves and has checkbox for whether to get emailed the volunteer survey

**Comment by brettevans** [comment]
Relates to having something like an iPad or a laptop out at an event for people to fill out information. Look at form integrations. Look at potential issues with deduplication if Contacts already exist and fill out the form again.

**Comment by hasuf** [comment]
Took a quick look at sharing salesforce surveys... ie,
1. log into https://na24.salesforce.com/home/home.jsp
2. browse over to surveys https://na24.salesforce.com/a0H/o
3. click on a survey. there's a way to "share email link anonymously", but if you go to one of the links (eg, https://c.na24.visual.force.com/apex/TakeSurvey?id=a0H1a0000003yikEAA&cId=none&caId=none ) in "incognito" or "private browsing" mode in a browser, salesforce requires you to log in...

**Comment by hasuf** [comment]
@hendrang Found a plugin called web2lead. Through this plugin, a survey can be created and be made accessible from any hosted page. The data gets saved in SalesForce (and a lead can automatically generated). Surveys can easily be cloned (ie, a template survey can be created, then clone for each new event.)

THE CATCH: However, a process would have to be created whereby the generated HTML is hosted by RMMFI. 

See https://teravisiontech.na24.visual.force.com/apex/multiple_Web2Lead_tab?sfdc.tabName=01r1a0000009ZEO&tsid=02u1a0000009i51

@switzersc, A question for Brendan... Does RMMFI have the capability to host new pages as new surveys are created per event??

**Comment by brettevans** [comment]
Thanks Joseph! Will discuss when we meet with Brendan.

**Comment by haydenevans** [comment]
Did we ever decide on where to host these lead forms? I believe we discussed a few options (S3, Dropbox, etc).

**Comment by lweeks4880** [comment]
Hayden, I wasn't part of the discussion on that. If that is the same form that I did the documentation for "Multiple Web2Lead" Plugin, I can save a copy of the form on G-Drive for now.

**Comment by lweeks4880** [comment]
Not sure where in the workflow we want this issue. I ended up closing it instead of just commenting.

**Comment by haydenevans** [comment]
Google Drive works fine as long as we can navigate to it. Did you ever get a final form to host, or are we still waiting on a finalized version?

**Comment by haydenevans** [comment]
And let's leave this In Progress for now until we host a final version of the form that is accessible via the web.
